require "yaml"
require "fileutils"

METADATA_KEYS = %w[display_name interface_style accent_color].freeze

def resolve_value(value, theme_data)
  colors = theme_data["colors"]

  return colors[value] if colors.key?(value)
  return theme_data[value] if METADATA_KEYS.include?(value)

  value
end

def format_css_value(property, resolved_value)
  case property
  when "-theme-display-name"
    "\"#{resolved_value}\""
  else
    resolved_value.to_s
  end
end

def generate_css(theme_data, sections)
  css = ""
  sections.each do |selector, properties|
    css += "#{selector} {\n"
    properties.each do |property, color_ref|
      resolved = resolve_value(color_ref.to_s, theme_data)
      formatted = format_css_value(property, resolved)
      css += "  #{property}: #{formatted};\n"
    end
    css += "}\n\n"
  end
  css
end

def generate_app_themes(themes, app_config)
  output_dir   = app_config["output_dir"]
  file_suffix  = app_config["file_suffix"] || ".css"
  sections     = app_config["sections"]

  FileUtils.mkdir_p(output_dir)

  themes.each do |_theme_name, theme_data|
    display_name = theme_data["display_name"]
    css          = generate_css(theme_data, sections)
    filename     = File.join(output_dir, "#{display_name}#{file_suffix}")
    File.write(filename, css)
    puts "Generated #{filename}"
  end
end

def generate_docs(themes, docs_dir)
  FileUtils.mkdir_p(docs_dir)

  md  = "# Solunized Color Scheme\n\n"
  md += "Solunized is a higher-contrast variation of Solarized that preserves Solarized's\n"
  md += "distinctive blue-teal background tint while increasing the contrast between\n"
  md += "background and foreground text for improved readability.\n\n"
  md += "This document is auto-generated by `generate_themes.rb`. Do not edit by hand.\n\n"

  themes.each do |_theme_name, theme_data|
    display_name    = theme_data["display_name"]
    interface_style = theme_data["interface_style"]
    colors          = theme_data["colors"]

    md += "## #{display_name}\n\n"
    md += "**Interface style:** #{interface_style}\n\n"
    md += "| Color Name | Hex Value | Swatch |\n"
    md += "|------------|-----------|--------|\n"
    colors.each do |name, value|
      md += "| `#{name}` | `#{value}` | ![#{value}](https://img.shields.io/badge/-%20-#{value.delete('#')}?style=flat-square) |\n"
    end
    md += "\n"
  end

  path = File.join(docs_dir, "colors.md")
  File.write(path, md)
  puts "Generated #{path}"
end

# Entry point
themes_yml   = ARGV[0] || "themes.yml"
apps_dir     = ARGV[1] || "applications"
docs_dir     = "docs"

themes = YAML.load_file(themes_yml)["themes"]

Dir.glob(File.join(apps_dir, "*.yml")).sort.each do |app_file|
  app_config = YAML.load_file(app_file)
  app_name   = app_config.keys.first
  puts "Processing application: #{app_name}"
  generate_app_themes(themes, app_config[app_name])
end

generate_docs(themes, docs_dir)
